version: '3.8'

services:
    rt1:
        image: snisioi/retele:2021
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
    rt2:
        image: snisioi/retele:2021
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
    rt3:
        image: snisioi/retele:2021
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz

networks:
    dmz: {}
